accounts:
  - name: equaman1
    coins: ["20000token", "200000000stake"]
  - name: Equaman4
    coins: ["10000token"]
validator:
  name: equaman2
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: equaman3
  coins: ["5token", "100000stake"]
